swagger: "2.0"
info:
  description: "RNA API for GA4GH consideration."
  version: "0.1.0"
  title: "GA4GH RNASeq API"
host: "ga4gh.org"
basePath: "/rna"
tags:
- name: "projects"
  description: "High level collection of studies"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/ga4gh-rnaseq/schema"
- name: "studies"
  description: "Collection of associated uniformly processed RNA samples"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/ga4gh-rnaseq/schema"
- name: "expressions"
  description: "Feature level expression data"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/ga4gh-rnaseq/schema"
- name: "getVersions"
  description: "Returns database release versions"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/ga4gh-rnaseq/schema"
- name: "changelog"
  description: "Returns change log for a release version"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/ga4gh-rnaseq/schema"
- name: "files"
  description: "Returns files"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/ga4gh-rnaseq/schema"
schemes:
- "http"
paths:
  /projects/search:
    get:
      tags:
      - "projects"
      summary: "Search for projects matching filters"
      description: "Search for projects matching filters"
      operationId: "searchProjects"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "tags"
        in: "query"
        description: "Comma separated tag list to filter by"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "version"
        in: "query"
        description: "version to return"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/project"
        400:
          description: "Error"
      security:
      - rna_auth:
        - "read:expression"
  /projects/{projectId}:
    get:
      tags:
      - "projects"
      summary: "Find project by ID"
      description: "Returns a single specified project"
      operationId: "getProjectById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "projectId"
        in: "path"
        description: "ID of project to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/project"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Project not found"
      security:
      - api_key: []
  /studies/search:
    get:
      tags:
      - "studies"
      summary: "Search for studies matching filters"
      description: "Search for studies matching filters"
      operationId: "searchStudies"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "tags"
        in: "query"
        description: "Comma separated tag list to filter by"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "version"
        in: "query"
        description: "version to return"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/study"
        400:
          description: "Error"
      security:
      - rna_auth:
        - "read:expression"
  /studies/{studyId}:
    get:
      tags:
      - "studies"
      summary: "Find study by ID"
      description: "Returns a single specified study"
      operationId: "getStudyById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "studyId"
        in: "path"
        description: "ID of study to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/study"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Study not found"
      security:
      - api_key: []
  /expressions/{expressionId}:
    get:
      tags:
      - "expressions"
      summary: "Find expression data by ID"
      description: "Returns a single specified expression matrix"
      operationId: "getExpressionById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "expressionId"
        in: "path"
        description: "ID of expression to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/expression"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Expression not found"
      security:
      - api_key: []
  /expressions/search:
    get:
      tags:
      - "expressions"
      summary: "Search for expressions matching filters"
      description: "Search for expressions matching filters"
      operationId: "searchExpressions"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "tags"
        in: "query"
        description: "Comma separated tag list to filter by"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "organism"
        in: "query"
        description: "organism to match"
        required: false
        type: "string"
      - name: "reference"
        in: "query"
        description: "genomic reference to filter by"
        required: false
        type: "string"
      - name: "annotation"
        in: "query"
        description: "annotation to filter by"
        required: false
        type: "string"
      - name: "tissue"
        in: "query"
        description: "tissue type to match"
        required: false
        type: "string"
      - name: "sampleID"
        in: "query"
        description: "sampleID to match"
        required: false
        type: "string"
      - name: "projectID"
        in: "query"
        description: "project to filter by"
        required: false
        type: "string"
      - name: "studyID"
        in: "query"
        description: "study to filter by"
        required: false
        type: "string"
      - name: "version"
        in: "query"
        description: "version to filter by"
        required: false
        type: "string"
      - name: "geneNameList"
        in: "query"
        description: "return only values for listed genes"
        required: false
        type: "array"
        items:
          type: "string"
      - name: "geneAccessionList"
        in: "query"
        description: "return only values for listed accession numbers"
        required: false
        type: "array"
        items:
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/expression"
        400:
          description: "Error"
      security:
      - rna_auth:
        - "read:expression"
  /getVersions:
    get:
      tags:
      - "getVersions"
      summary: "Get release versions of database"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "string"
        400:
          description: "Invalid tag value"
      security:
      - rna_auth:
        - "read:expression"
  /changelog/{version}:
    get:
      tags:
      - "changelog"
      summary: "Get change log for a specific release version"
      description: "Returns changes associated with specified database release version"
      operationId: "getChangeLog"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "version"
        in: "path"
        description: "release version"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/changeLog"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Change log not found"
      security:
      - api_key: []
  /files/{fileID}:
    get:
      tags:
      - "files"
      summary: "Get specific file"
      description: "Returns download URL for file"
      operationId: "getFile"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "fileID"
        in: "path"
        description: "file ID"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/file"
        400:
          description: "Invalid ID supplied"
        404:
          description: "File not found"
      security:
      - api_key: []
  /files/search:
    get:
      tags:
      - "files"
      summary: "Search for files matching filters"
      description: "Search for files matching filters.  Returns download URL or manifest of download URLs for matching file(s)"
      operationId: "searchFiles"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "tags"
        in: "query"
        description: "Comma separated tag list to filter by"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "projectID"
        in: "query"
        description: "ProjectID to filter by"
        required: false
        type: "string"
      - name: "studyID"
        in: "query"
        description: "StudyID to filter by"
        required: false
        type: "string"
      - name: "fileType"
        in: "query"
        description: "File type to filter by"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/file"
        400:
          description: "Error"
      security:
      - rna_auth:
        - "read:expression"
securityDefinitions:
  rna_auth:
    type: "oauth2"
    authorizationUrl: "http://ga4gh.org/oauth/dialog"
    flow: "implicit"
    scopes:
      read:expression: "read expression"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  project:
    type: "object"
    properties:
      id:
        type: "string"
      version:
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      name:
        type: "string"
      description:
        type: "string"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/ga4gh-rnaseq/schema"
    xml:
      name: "project"
  study:
    type: "object"
    properties:
      id:
        type: "string"
      version:
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      name:
        type: "string"
      description:
        type: "string"
      parentProjectID:
        type: "string"
      patientList:
        type: "array"
        items:
          type: "string"
      sampleList:
        type: "array"
        items:
          type: "string"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/ga4gh-rnaseq/schema"
    xml:
      name: "study"
  expression:
    type: "object"
    description: "Matrix of expression values."
    properties:
      id:
        type: "string"
      version:
        type: "string"
      parentStudyID:
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      organism:
        type: "string"
      tissue:
        type: "string"
      units:
        type: "string"
      sampleID:
        type: "string"
      expressionMatrix:
        type: "array"
        items:
          type: "array"
          items:
            type: "number"
            format: "float"
      rowLabels:
        type: "array"
        items:
          type: "string"
      columnLabels:
        type: "array"
        items:
          type: "string"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/ga4gh-rnaseq/schema"
    xml:
      name: "expression"
  sequenceAnnotation:
    type: "object"
    description: "top level genomic annotation object corresponding to a single GFF file"
    properties:
      id:
        type: "string"
      version:
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      referenceGenomeID:
        type: "string"
      name:
        type: "string"
      featureList:
        type: "array"
        items:
          type: "string"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/ga4gh-rnaseq/schema"
    xml:
      name: "sequenceAnnotation"
  feature:
    type: "object"
    description: "equivalent to a line of a GFF file"
    properties:
      id:
        type: "string"
      version:
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      accession:
        type: "string"
      name:
        type: "string"
      seqName:
        type: "string"
      start:
        type: "integer"
      end:
        type: "integer"
      strand:
        type: "string"
      featureType:
        type: "string"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/ga4gh-rnaseq/schema"
    xml:
      name: "feature"
  changeLog:
    type: "object"
    description: "list of changes to the database associated with a version update"
    properties:
      version:
        type: "string"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/ga4gh-rnaseq/schema"
    xml:
      name: "changeLog"
  file:
    type: "object"
    description: "URL and type for raw data and analysis pipeline files"
    properties:
      id:
        type: "string"
      version:
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      fileType:
        type: "string"
      studyID:
        type: "string"
      URL:
        type: "string"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/ga4gh-rnaseq/schema"
    xml:
      name: "file"
externalDocs:
  description: "Find out more about GA4GH"
  url: "http://ga4gh.org"
